development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:bad165e2af8499b04e4c8c83640ea6fb@barreleye.redistogo.com:10937/
