# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &development
  secret_key_base: e369575030a3ac3c396ccb152187c43e61e03721a910e5a90a1153c0f06b04c2a2b750ffb0020152a6580c261cb86ae11936f0ea2deec6380012b33d35b7fd3c
  email_recipients_interceptors: <%= ENV['EMAIL_RECIPIENTS_INTERCEPTOR'] %>
  encryption_salt: e9b52b84b6f12903d7bcd5918ccffab6a89b028f04eab343445588f243df4c000f1a66d09022dd26ba97ada4171263bf2615c3a578549e2f39591a8acf5386cf

test:
  <<: *development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  encryption_salt: <%= ENV['ENCRYPTION_SALT'] %>
